on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Lints:
    runs-on: UbuntuLatest32Cores128G
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Check Nixpkgs input
        uses: DeterminateSystems/flake-checker-action@main

      - name: Check EditorConfig conformance
        if: always()
        run: nix develop --command check-editorconfig

      - name: Check Spelling
        if: always()
        run: nix develop --command check-spelling

      - name: Check nixpkgs-fmt formatting
        if: always()
        run: nix develop --command check-nixpkgs-fmt

      - name: Check rustfmt
        if: always()
        run: nix develop --command check-rustfmt

      - name: Check Clippy
        if: always()
        run: nix develop --command check-clippy

  DeterminateCI:
    needs:
      - Lints
    uses: DeterminateSystems/ci/.github/workflows/workflow.yml@main
    permissions:
      id-token: "write"
      contents: "read"
    with:
      visibility: private
      runner-map: |
        {
          "aarch64-darwin": "macos-latest-xlarge",
          "aarch64-linux": "UbuntuLatest32Cores128GArm",
          "i686-linux": "UbuntuLatest32Cores128G",
          "x86_64-darwin": "macos-latest-xlarge",
          "x86_64-linux": "UbuntuLatest32Cores128G"
        }
